### ISSUE TITLE
qm2mfast unsupported operand error within archive.read_waveform_data

### ISSUE THREAD

**Issue by jamiemccann** [hemmelig/AnisotropIO#1]
**Describe the bug**
In https://github.com/hemmelig/AnisotropIO/blob/main/anisotropio/translators/qm2X.py, specifically the section:

```
        # --- Find min/max pick times and use to query data from archive ---
        min_time, max_time = picks["PickTime"].min(), picks["PickTime"].max()
        data = archive.read_waveform_data(
            min_time - 15,
            max_time + 15,
            pre_pad=1.5,
            post_pad=1.5
```
I get the following error:

```
---> 68     min_time - 15,

TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

**To Reproduce**
Copy prepare_MFAST_from_QM_run.py into jupyter notebook and set appropriate base_path and archive_path, run code 

**Expected behavior**
qm2mfast function should run

**Desktop (please complete the following information):**
 - Operating System: Ubuntu
 - Python version: 3.8
 - AnisotropIO version: 0.0.1

**Additional context**
Compared to previous script you generated with me in Cambridge, the use of obspy.UTCDateTime() is done later, so it is possibly that when min_time and max_time are created, they are created as strings (and so the indexing of picks['PickTime'] will still work), however the use of arithmetic operators won't wok hence the error

**Comment by hemmelig** [comment]
Yep, good spot - just need to add this below line 61:

```
        # --- Convert picks to UTCDateTime objects ---
        picks["PickTime"] = picks["PickTime"].apply(
            lambda x: obspy.UTCDateTime(x)
        )
```

Can also then delete line 84 (`pick_time = obspy.UTCDateTime(pick.PickTime)`) as we will already have converted everything to UTCDateTime.

How about you make this change to get a bit of git practice? In general, this process would look something like this:

1. Create a new branch, from `main`, where you will make the fix - perhaps with a name like `bugfix_convert_str2UTCDateTime`.
2. Make the fix
3. Add the changed file the "staging area"
4. Commit the changes - make sure to write a commit message with sufficient information! Use `git commit` - this will open a file in vim that you can write the commit message in. The top line should be a "title" - something like `:bug: Convert pick times to UTCDateTime`. Then leave a space and write your description. You can reference this issue in the commit message using the #1 - so including something like "This commit fixes the bug raised in Issue #1".
5. Push your changes to the remote branch
6. Open a Pull Request through the GitHub interface - we can take it from there!
